cook/urls.py
from django.urls import path
from . import views

app_name='cook'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('upload/',views.CreateView.as_view(),name='upload'),
    path('detail/<int:pk>',views.DetailView.as_view(),name='detail'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cook.urls')),
]
# 

cook/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title=models.CharField('タイトル',max_length=20)
    text=models.TextField('本文')
    created_at=models.DateTimeField('日付',default=timezone.now)
    
    def __str__(self):
        return self.title[:10]

cook/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','text','created_at')
        

cook/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import PostCreateForm
from .models import Post

class IndexView(generic.ListView):
    model=Post
    
class CreateView(generic.CreateView):
    model=Post
    form_class=PostCreateForm
    success_url=reverse_lazy('cook:index')
    
class DetailView(generic.DetailView):
    model=Post

cook/templates/cook/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>料理投稿アプリ</title>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navber-dark bg-dark">
    <a class="navbar-brand" href="{% url 'cook:index' %}">料理投稿アプリ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'cook:index' %}">List<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cook:upload' %}">Create</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <div class="container mt-5">
  <div class="row">
    <div class="col-md-8">
    {% block content %}
    {% endblock %}
    </div>

    <div class="col-md-4">
    <p>カテゴリー一覧</p>
    </div>
  </div>
  </div>
  

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

cook/templates/cook/post_detail.html
{% extends 'cook/base.html' %}

{% block content %}
<div class="card">
    <div class="card-header bg-dark text-white">
        <p>{{post.title}}</p>
    </div>
    <div class="card-body">
      <p>{{post.text|linebreaksbr}}</p>

    </div>
</div>

{% endblock %}

cook/templates/cook/post_form.html
{% extends 'cook/base.html' %}

{% block content %}
<form action="" method="POST">
    
    {% for field in form %}
    <p>{{ field.label_tag }}</p>
    <p>{{field}}</p>
    {% endfor %}
<button type="submit">投稿する</button>
{% csrf_token %}
</form>
{% endblock %}

cook/templates/cook/post_list.html
{% extends 'cook/base.html' %}

{% block content %}
<div class="jumbotron">
  <h2 class="display-3">料理のレシピを投稿しよう！</h2>
  <p class="lead">自分のお気に入りの料理を紹介しよう。</p>
  <hr class="my-2">
  <p class="lead">
    <a class="btn btn-primary btn-lg btn-dark" href="#!" role="button">投稿する</a>
  </p>
</div>


{% for post in post_list %}
<div class="card mb-3">
    <h4 class="card-header bg-dark text-white">
    {{post.title}}
    </h4>
    <div class="card-body">
      <p>{{post.created_at}}</p>
      <a href="{% url 'cook:detail' post.pk %}" class="btn btn-primary btn-dark">続きを読む</a>
    </div>
</div>
  
{% endfor %}
{% endblock %}